# local machine settings
#
# For example, on Linux on a PC this will likely work:
DEPEND = g++
CC = g++ -Wall
RELEASE_FLAGS = -O3 -DNDEBUG -funroll-loops
DEBUG_FLAGS = -g
LINK = g++
LINK_LIBS = -lm -lGL -lGLU -lglut

# On Mac OS X this should work:
# DEPEND = g++
# CC = g++ -Wall
# RELEASE_FLAGS = -O3 -DNDEBUG -funroll-loops
# DEBUG_FLAGS = -g
# LINK = g++
# LINK_LIBS = -lm -lobjc -framework OpenGL -framework GLUT
